version: v2alpha4
pipeline:
  stages:
    "Image build":
      branch: "!main"
      imageBuild:
        name: platform/pipeshubai
        tags:
          - oddyssey1.0.0.1-1 #TODO
        securityScan:
          failSeverity: CRITICAL
          issueAllowlist:
            - CVE-2026-49261
            - CVE-2026-44172
            - CVE-2026-6653
            - CVE-2026-85394
            - CVE-2026-90711
            - CVE-2026-8838
            - CVE-2026-106445
            - CVE-2026-106446
        context: .
        push: true #TODO
    "Image build and push":
      branch: "main"
      imageBuild:
        name: platform/pipeshubai
        tags:
          - oddyssey1.0.0.1
        securityScan:
          failSeverity: CRITICAL
          issueAllowlist:
            - CVE-2026-49261
            - CVE-2026-44172
            - CVE-2026-6653
            - CVE-2026-85394
            - CVE-2026-90711
            - CVE-2026-8838
            - CVE-2026-106445
            - CVE-2026-106446
        context: .
        push: true